apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-opencloselog-report
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: connectionString
      value: "amqp://rabbitmq:5672"
    - name: durable
      value: "true"
    - name: deletedWhenUnused
      value: "false"
    - name: deliveryMode
      value: "2"
    - name: requeueInFailure
      value: "true"
    - name: prefetchCount
      value: "10"
    - name: publisherConfirm
      value: "true"
    - name: enableDeadLetter
      value: "true"
