apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    value: "mongodb:27017"
  - name: databaseName
    value: "dapr_statestore"
  - name: collectionName
    value: "state"
  - name: actorStateStore
    value: "false"
  - name: operationTimeout
    value: "5s"
