apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: terminalstore
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    value: "mongodb:27017"
  - name: databaseName
    value: "dapr_terminalstore"
  - name: collectionName
    value: "terminal_state"
  - name: actorStateStore
    value: "false"
  - name: operationTimeout
    value: "5s"
