# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: item_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'item_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12item_service.proto\x12\x0citem_service\"b\n\x11ItemDetailRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x12\n\nstore_code\x18\x02 \x01(\t\x12\x11\n\titem_code\x18\x03 \x01(\t\x12\x13\n\x0bterminal_id\x18\x04 \x01(\t\"\xd0\x01\n\x12ItemDetailResponse\x12\x11\n\titem_code\x18\x01 \x01(\t\x12\x11\n\titem_name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x05\x12\x10\n\x08tax_rate\x18\x04 \x01(\x05\x12\x15\n\rcategory_code\x18\x05 \x01(\t\x12\x0f\n\x07\x62\x61rcode\x18\x06 \x01(\t\x12\x11\n\tis_active\x18\x07 \x01(\x08\x12\x12\n\ncreated_at\x18\x08 \x01(\t\x12\x12\n\nupdated_at\x18\t \x01(\t\x12\x10\n\x08tax_code\x18\n \x01(\t2a\n\x0bItemService\x12R\n\rGetItemDetail\x12\x1f.item_service.ItemDetailRequest\x1a .item_service.ItemDetailResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'item_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMDETAILREQUEST']._serialized_start=36
  _globals['_ITEMDETAILREQUEST']._serialized_end=134
  _globals['_ITEMDETAILRESPONSE']._serialized_start=137
  _globals['_ITEMDETAILRESPONSE']._serialized_end=345
  _globals['_ITEMSERVICE']._serialized_start=347
  _globals['_ITEMSERVICE']._serialized_end=444
# @@protoc_insertion_point(module_scope)
