[loggers]
keys=root, pymongo, requestLogger, httpcore, auditLogger

[handlers]
keys=consoleHandler, fileHandler, requestFileHandler, auditFileHandler

[formatters]
keys=sampleFormatter, requestFormatter, auditFormatter

[logger_root]
level=DEBUG
handlers=consoleHandler, fileHandler

[logger_requestLogger]
level=DEBUG
handlers=requestFileHandler
qualname=requestLogger
propagate=0

[logger_pymongo]
level=WARNING
handlers=consoleHandler, fileHandler
qualname=pymongo

[logger_httpcore]
level=WARNING
handlers=consoleHandler, fileHandler
qualname=httpcore

[logger_auditLogger]
level=INFO
handlers=consoleHandler, auditFileHandler
qualname=audit
propagate=0

[handler_consoleHandler]
class=logging.StreamHandler
level=DEBUG
formatter=sampleFormatter
args=(sys.stdout,)

[handler_fileHandler]
class=logging.FileHandler
level=DEBUG
formatter=sampleFormatter
args=('app.log', 'a', 'utf-8')

[handler_requestFileHandler]
class=logging.FileHandler
level=DEBUG
formatter=requestFormatter
args=('request.log', 'a', 'utf-8')

[handler_auditFileHandler]
class=logging.FileHandler
level=INFO
formatter=auditFormatter
args=('audit.log', 'a', 'utf-8')

[formatter_sampleFormatter]
format=%(asctime)s [%(levelname)s] %(name)s: %(message)s
datefmt=

[formatter_requestFormatter]
format=%(asctime)s : %(message)s

[formatter_auditFormatter]
format=%(asctime)s [%(levelname)s] AUDIT: %(message)s
datefmt=